server:
  port: 80
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.104
    port: 6379
wechat:
  mpAppId: mpAppId
  mpAppSecret: mpAppSecret
  openAppId: openAppId
  openAppSecret: openAppSecret
  mchId: mchId
  mchKey: mchKey
  keyPath: keyPath
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: orderStatus

projectUrl:
  wechatMpAuthorize:
  wechatOpenAuthorize:
  sell:
logging:
  level:
    com.imooc.sell.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: E:/workspace/idea/springbootdemo/logs
##  file: E:/workspace/idea/springbootdemo/logs/sell.%d.log
#  level:
#    com.imooc.sell.LoggerTest: debug
